<?php

declare(strict_types = 1);

namespace ValanticSpryker\Zed\PriceProductCustomerGroupStorage\Persistence\Propel;

use Orm\Zed\PriceProductCustomerGroupStorage\Persistence\Base\VsyPriceProductConcreteCustomerGroupStorageQuery as BaseVsyPriceProductConcreteCustomerGroupStorageQuery;

class AbstractVsyPriceProductConcreteCustomerGroupStorageQuery extends BaseVsyPriceProductConcreteCustomerGroupStorageQuery
{
}
