<?php

declare(strict_types = 1);

namespace ValanticSpryker\Zed\PriceProductCustomerGroupStorage\Persistence\Propel;

use Orm\Zed\PriceProductCustomerGroupStorage\Persistence\Base\VsyPriceProductAbstractCustomerGroupStorageQuery as BaseVsyPriceProductAbstractCustomerGroupStorageQuery;

class AbstractVsyPriceProductAbstractCustomerGroupStorageQuery extends BaseVsyPriceProductAbstractCustomerGroupStorageQuery
{
}
